<a href="https://colab.research.google.com/github/anny17/Dermatrology-predictions/blob/master/Dermatrologyfinal.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd
import numpy as np

In [0]:
dermatdata = pd.read_csv("https://raw.githubusercontent.com/datasets/dermatology/master/data/dermatology.csv", delimiter = ',')

In [0]:
dermatdata.head(10)

,erythema,scaling,definite_borders,itching,koebner_phenomenon,polygonal_papules,follicular_papules,oral_mucosal_involvement,knee_and_elbow_involvement,scalp_involvement,...,disappearance_of_the_granular_layer,vacuolisation_and_damage_of_basal_layer,spongiosis,saw-tooth_appearance_of_retes,follicular_horn_plug,perifollicular_parakeratosis,inflammatory_monoluclear_inflitrate,band-like_infiltrate,age,class
0,2,2,0,3,0,0,0,0,1,0,...,0,0,3,0,0,0,1,0,55.0,2
1,3,3,3,2,1,0,0,0,1,1,...,0,0,0,0,0,0,1,0,8.0,1
2,2,1,2,3,1,3,0,3,0,0,...,0,2,3,2,0,0,2,3,26.0,3
3,2,2,2,0,0,0,0,0,3,2,...,3,0,0,0,0,0,3,0,40.0,1
4,2,3,2,2,2,2,0,2,0,0,...,2,3,2,3,0,0,2,3,45.0,3
5,2,3,2,0,0,0,0,0,0,0,...,0,0,2,0,0,0,1,0,41.0,2
6,2,1,0,2,0,0,0,0,0,0,...,0,0,0,0,0,0,2,0,18.0,5
7,2,2,3,3,3,3,0,2,0,0,...,2,2,3,2,0,0,3,3,57.0,3
8,2,2,1,0,2,0,0,0,0,0,...,0,0,2,0,0,0,2,0,22.0,4
9,2,2,1,0,1,0,0,0,0,0,...,0,0,2,0,0,0,2,0,30.0,4

In [0]:
dermatdata.describe()

,erythema,scaling,definite_borders,itching,koebner_phenomenon,polygonal_papules,follicular_papules,oral_mucosal_involvement,knee_and_elbow_involvement,scalp_involvement,...,disappearance_of_the_granular_layer,vacuolisation_and_damage_of_basal_layer,spongiosis,saw-tooth_appearance_of_retes,follicular_horn_plug,perifollicular_parakeratosis,inflammatory_monoluclear_inflitrate,band-like_infiltrate,age,class
count,366.000000,366.000000,366.000000,366.000000,366.000000,366.000000,366.000000,366.000000,366.000000,366.000000,...,366.000000,366.000000,366.000000,366.000000,366.000000,366.000000,366.000000,366.000000,358.000000,366.000000
mean,2.068306,1.795082,1.549180,1.366120,0.633880,0.448087,0.166667,0.377049,0.614754,0.519126,...,0.464481,0.456284,0.953552,0.453552,0.103825,0.114754,1.866120,0.554645,36.296089,2.803279
std,0.664753,0.701527,0.907525,1.138299,0.908016,0.957327,0.570588,0.834147,0.982979,0.905639,...,0.864899,0.954873,1.130172,0.954744,0.450433,0.488723,0.726108,1.105908,15.324557,1.597803
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
25%,2.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,25.000000,1.000000
50%,2.000000,2.000000,2.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,0.000000,35.000000,3.000000
75%,2.000000,2.000000,2.000000,2.000000,1.000000,0.000000,0.000000,0.000000,1.000000,1.000000,...,1.000000,0.000000,2.000000,0.000000,0.000000,0.000000,2.000000,0.000000,49.750000,4.000000
max,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,...,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,75.000000,6.000000

In [0]:
dermatdata.dtypes

erythema                                      int64
scaling                                       int64
definite_borders                              int64
itching                                       int64
koebner_phenomenon                            int64
polygonal_papules                             int64
follicular_papules                            int64
oral_mucosal_involvement                      int64
knee_and_elbow_involvement                    int64
scalp_involvement                             int64
family_history                                int64
melanin_incontinence                          int64
eosinophils_in_the_infiltrate                 int64
pnl_infiltrate                                int64
fibrosis_of_the_papillary_dermis              int64
exocytosis                                    int64
acanthosis                                    int64
hyperkeratosis                                int64
parakeratosis                                 int64
clubbing_of_the_rete_ridges                   int64
elongation_of_the_rete_ridges                 int64
thinning_of_the_suprapapillary_epidermis      int64
spongiform_pustule                            int64
munro_microabcess                             int64
focal_hypergranulosis                         int64
disappearance_of_the_granular_layer           int64
vacuolisation_and_damage_of_basal_layer       int64
spongiosis                                    int64
saw-tooth_appearance_of_retes                 int64
follicular_horn_plug                          int64
perifollicular_parakeratosis                  int64
inflammatory_monoluclear_inflitrate           int64
band-like_infiltrate                          int64
age                                         float64
class                                         int64
dtype: object

In [0]:
d = dermatdata

In [0]:
d.tail()

,erythema,scaling,definite_borders,itching,koebner_phenomenon,polygonal_papules,follicular_papules,oral_mucosal_involvement,knee_and_elbow_involvement,scalp_involvement,...,disappearance_of_the_granular_layer,vacuolisation_and_damage_of_basal_layer,spongiosis,saw-tooth_appearance_of_retes,follicular_horn_plug,perifollicular_parakeratosis,inflammatory_monoluclear_inflitrate,band-like_infiltrate,age,class
361,2,1,1,0,1,0,0,0,0,0,...,0,0,1,0,0,0,2,0,25.0,4
362,3,2,1,0,1,0,0,0,0,0,...,1,0,1,0,0,0,2,0,36.0,4
363,3,2,2,2,3,2,0,2,0,0,...,0,3,0,3,0,0,2,3,28.0,3
364,2,1,3,1,2,3,0,2,0,0,...,0,2,0,1,0,0,2,3,50.0,3
365,3,2,2,0,0,0,0,0,3,3,...,2,0,0,0,0,0,3,0,35.0,1

In [0]:
d.isnull().sum()

erythema                                    0
scaling                                     0
definite_borders                            0
itching                                     0
koebner_phenomenon                          0
polygonal_papules                           0
follicular_papules                          0
oral_mucosal_involvement                    0
knee_and_elbow_involvement                  0
scalp_involvement                           0
family_history                              0
melanin_incontinence                        0
eosinophils_in_the_infiltrate               0
pnl_infiltrate                              0
fibrosis_of_the_papillary_dermis            0
exocytosis                                  0
acanthosis                                  0
hyperkeratosis                              0
parakeratosis                               0
clubbing_of_the_rete_ridges                 0
elongation_of_the_rete_ridges               0
thinning_of_the_suprapapillary_epidermis    0
spongiform_pustule                          0
munro_microabcess                           0
focal_hypergranulosis                       0
disappearance_of_the_granular_layer         0
vacuolisation_and_damage_of_basal_layer     0
spongiosis                                  0
saw-tooth_appearance_of_retes               0
follicular_horn_plug                        0
perifollicular_parakeratosis                0
inflammatory_monoluclear_inflitrate         0
band-like_infiltrate                        0
age                                         8
class                                       0
dtype: int64

In [0]:
d['age'] = d.age.fillna(d.age.mean())

In [0]:
d.isnull().sum()

erythema                                    0
scaling                                     0
definite_borders                            0
itching                                     0
koebner_phenomenon                          0
polygonal_papules                           0
follicular_papules                          0
oral_mucosal_involvement                    0
knee_and_elbow_involvement                  0
scalp_involvement                           0
family_history                              0
melanin_incontinence                        0
eosinophils_in_the_infiltrate               0
pnl_infiltrate                              0
fibrosis_of_the_papillary_dermis            0
exocytosis                                  0
acanthosis                                  0
hyperkeratosis                              0
parakeratosis                               0
clubbing_of_the_rete_ridges                 0
elongation_of_the_rete_ridges               0
thinning_of_the_suprapapillary_epidermis    0
spongiform_pustule                          0
munro_microabcess                           0
focal_hypergranulosis                       0
disappearance_of_the_granular_layer         0
vacuolisation_and_damage_of_basal_layer     0
spongiosis                                  0
saw-tooth_appearance_of_retes               0
follicular_horn_plug                        0
perifollicular_parakeratosis                0
inflammatory_monoluclear_inflitrate         0
band-like_infiltrate                        0
age                                         0
class                                       0
dtype: int64

In [0]:
d.dtypes

erythema                                      int64
scaling                                       int64
definite_borders                              int64
itching                                       int64
koebner_phenomenon                            int64
polygonal_papules                             int64
follicular_papules                            int64
oral_mucosal_involvement                      int64
knee_and_elbow_involvement                    int64
scalp_involvement                             int64
family_history                                int64
melanin_incontinence                          int64
eosinophils_in_the_infiltrate                 int64
pnl_infiltrate                                int64
fibrosis_of_the_papillary_dermis              int64
exocytosis                                    int64
acanthosis                                    int64
hyperkeratosis                                int64
parakeratosis                                 int64
clubbing_of_the_rete_ridges                   int64
elongation_of_the_rete_ridges                 int64
thinning_of_the_suprapapillary_epidermis      int64
spongiform_pustule                            int64
munro_microabcess                             int64
focal_hypergranulosis                         int64
disappearance_of_the_granular_layer           int64
vacuolisation_and_damage_of_basal_layer       int64
spongiosis                                    int64
saw-tooth_appearance_of_retes                 int64
follicular_horn_plug                          int64
perifollicular_parakeratosis                  int64
inflammatory_monoluclear_inflitrate           int64
band-like_infiltrate                          int64
age                                         float64
class                                         int64
dtype: object

In [0]:
d['age'] = d.age.astype(int)

In [0]:
d.dtypes

erythema                                    int64
scaling                                     int64
definite_borders                            int64
itching                                     int64
koebner_phenomenon                          int64
polygonal_papules                           int64
follicular_papules                          int64
oral_mucosal_involvement                    int64
knee_and_elbow_involvement                  int64
scalp_involvement                           int64
family_history                              int64
melanin_incontinence                        int64
eosinophils_in_the_infiltrate               int64
pnl_infiltrate                              int64
fibrosis_of_the_papillary_dermis            int64
exocytosis                                  int64
acanthosis                                  int64
hyperkeratosis                              int64
parakeratosis                               int64
clubbing_of_the_rete_ridges                 int64
elongation_of_the_rete_ridges               int64
thinning_of_the_suprapapillary_epidermis    int64
spongiform_pustule                          int64
munro_microabcess                           int64
focal_hypergranulosis                       int64
disappearance_of_the_granular_layer         int64
vacuolisation_and_damage_of_basal_layer     int64
spongiosis                                  int64
saw-tooth_appearance_of_retes               int64
follicular_horn_plug                        int64
perifollicular_parakeratosis                int64
inflammatory_monoluclear_inflitrate         int64
band-like_infiltrate                        int64
age                                         int64
class                                       int64
dtype: object

In [0]:
d.columns

Index(['erythema', 'scaling', 'definite_borders', 'itching',
       'koebner_phenomenon', 'polygonal_papules', 'follicular_papules',
       'oral_mucosal_involvement', 'knee_and_elbow_involvement',
       'scalp_involvement', 'family_history', 'melanin_incontinence',
       'eosinophils_in_the_infiltrate', 'pnl_infiltrate',
       'fibrosis_of_the_papillary_dermis', 'exocytosis', 'acanthosis',
       'hyperkeratosis', 'parakeratosis', 'clubbing_of_the_rete_ridges',
       'elongation_of_the_rete_ridges',
       'thinning_of_the_suprapapillary_epidermis', 'spongiform_pustule',
       'munro_microabcess', 'focal_hypergranulosis',
       'disappearance_of_the_granular_layer',
       'vacuolisation_and_damage_of_basal_layer', 'spongiosis',
       'saw-tooth_appearance_of_retes', 'follicular_horn_plug',
       'perifollicular_parakeratosis', 'inflammatory_monoluclear_inflitrate',
       'band-like_infiltrate', 'age', 'class'],
      dtype='object')

In [0]:
target = d.drop(columns=['erythema', 'scaling', 'definite_borders', 'itching',
       'koebner_phenomenon', 'polygonal_papules', 'follicular_papules',
       'oral_mucosal_involvement', 'knee_and_elbow_involvement',
       'scalp_involvement', 'family_history', 'melanin_incontinence',
       'eosinophils_in_the_infiltrate', 'pnl_infiltrate',
       'fibrosis_of_the_papillary_dermis', 'exocytosis', 'acanthosis',
       'hyperkeratosis', 'parakeratosis', 'clubbing_of_the_rete_ridges',
       'elongation_of_the_rete_ridges',
       'thinning_of_the_suprapapillary_epidermis', 'spongiform_pustule',
       'munro_microabcess', 'focal_hypergranulosis',
       'disappearance_of_the_granular_layer',
       'vacuolisation_and_damage_of_basal_layer', 'spongiosis',
       'saw-tooth_appearance_of_retes', 'follicular_horn_plug',
       'perifollicular_parakeratosis', 'inflammatory_monoluclear_inflitrate',
       'band-like_infiltrate', 'age'])

In [0]:
target

     class
0        2
1        1
2        3
3        1
4        3
5        2
6        5
7        3
8        4
9        4
10       1
11       2
12       2
13       1
14       3
15       4
16       2
17       1
18       3
19       5
20       6
21       2
22       5
23       3
24       5
25       1
26       6
27       5
28       2
29       3
..     ...
336      1
337      5
338      5
339      3
340      1
341      5
342      5
343      6
344      6
345      4
346      4
347      6
348      6
349      6
350      1
351      1
352      1
353      5
354      5
355      1
356      1
357      1
358      1
359      2
360      2
361      4
362      4
363      3
364      3
365      1

[366 rows x 1 columns]

In [0]:
values = d.drop(columns = ['class'])

In [0]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(values,target,random_state=1,test_size=0.3)

In [0]:
values

,erythema,scaling,definite_borders,itching,koebner_phenomenon,polygonal_papules,follicular_papules,oral_mucosal_involvement,knee_and_elbow_involvement,scalp_involvement,...,focal_hypergranulosis,disappearance_of_the_granular_layer,vacuolisation_and_damage_of_basal_layer,spongiosis,saw-tooth_appearance_of_retes,follicular_horn_plug,perifollicular_parakeratosis,inflammatory_monoluclear_inflitrate,band-like_infiltrate,age
0,2,2,0,3,0,0,0,0,1,0,...,0,0,0,3,0,0,0,1,0,55
1,3,3,3,2,1,0,0,0,1,1,...,0,0,0,0,0,0,0,1,0,8
2,2,1,2,3,1,3,0,3,0,0,...,2,0,2,3,2,0,0,2,3,26
3,2,2,2,0,0,0,0,0,3,2,...,0,3,0,0,0,0,0,3,0,40
4,2,3,2,2,2,2,0,2,0,0,...,2,2,3,2,3,0,0,2,3,45
5,2,3,2,0,0,0,0,0,0,0,...,0,0,0,2,0,0,0,1,0,41
6,2,1,0,2,0,0,0,0,0,0,...,0,0,0,0,0,0,0,2,0,18
7,2,2,3,3,3,3,0,2,0,0,...,0,2,2,3,2,0,0,3,3,57
8,2,2,1,0,2,0,0,0,0,0,...,0,0,0,2,0,0,0,2,0,22
9,2,2,1,0,1,0,0,0,0,0,...,0,0,0,2,0,0,0,2,0,30
10,3,3,2,1,1,0,0,0,2,2,...,0,0,0,0,0,0,0,1,0,20
11,2,2,0,3,0,0,0,0,0,0,...,0,0,0,3,0,0,0,1,0,21
12,3,3,1,2,0,0,0,0,0,1,...,0,0,0,2,0,0,0,1,0,22
13,2,3,3,0,0,0,0,0,1,1,...,0,0,0,0,0,0,0,2,0,10
14,2,2,3,3,0,3,0,2,0,0,...,2,0,3,0,3,0,0,1,3,65
15,1,1,0,1,3,0,0,0,0,0,...,0,0,0,2,0,0,0,2,0,40
16,2,2,1,3,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,30
17,3,3,3,0,0,0,0,0,3,3,...,0,3,0,0,0,0,0,2,0,38
18,2,1,3,3,3,3,0,0,2,0,...,3,0,2,0,3,0,0,2,3,23
19,1,1,0,3,0,0,0,0,0,0,...,0,0,0,1,0,0,0,2,0,17
20,2,1,1,2,0,0,3,0,1,2,...,0,0,0,0,0,1,2,1,0,8
21,3,2,2,0,0,0,0,0,0,0,...,0,0,0,3,0,0,0,2,0,51
22,2,2,0,2,0,0,0,0,0,0,...,0,0,0,1,0,1,0,2,0,42
23,2,2,2,3,2,2,0,2,0,0,...,3,0,3,0,2,0,0,2,3,44
24,2,0,0,3,0,0,0,0,0,0,...,0,0,0,0,0,0,0,2,0,22
25,2,1,1,0,1,0,0,0,2,0,...,0,2,0,0,0,0,0,2,0,33
26,1,1,0,1,0,0,3,0,1,0,...,1,0,0,1,0,2,2,1,0,10
27,1,2,2,3,0,0,0,0,0,0,...,0,0,0,1,0,0,0,3,0,17
28,3,2,2,2,0,0,0,0,0,0,...,0,0,0,2,0,1,1,2,0,43
29,1,1,2,3,2,2,0,3,0,0,...,3,0,3,0,3,1,0,2,3,50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
336,2,3,2,1,0,0,0,0,2,2,...,0,2,0,0,0,0,0,2,0,60
337,2,1,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,2,0,42
338,3,1,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,2,0,32
339,2,1,2,2,2,3,0,2,0,0,...,3,0,2,0,2,0,0,2,3,51
340,2,2,3,0,0,0,0,0,2,2,...,0,2,0,0,0,0,0,2,0,33
341,1,1,0,2,0,0,0,0,0,0,...,0,0,0,0,0,0,0,2,0,68
342,2,0,1,2,0,0,0,0,0,0,...,0,0,0,0,0,0,0,2,0,50
343,2,2,2,0,0,0,1,0,1,0,...,0,0,0,1,0,3,2,2,0,9
344,2,2,1,0,0,0,2,0,2,0,...,0,0,0,2,0,2,3,1,0,16
345,2,2,2,1,1,0,0,0,0,0,...,0,0,0,2,0,0,0,2,0,35
346,2,2,2,1,0,0,0,0,0,0,...,0,1,0,2,0,0,0,2,0,40
347,2,2,0,1,0,0,2,0,2,0,...,0,0,0,1,0,2,2,2,0,22
348,3,2,2,0,0,0,3,0,1,0,...,0,0,0,2,0,3,2,2,0,10
349,2,2,1,0,0,0,2,0,2,0,...,0,0,0,3,0,2,2,2,0,7
350,1,2,2,2,0,0,0,0,2,2,...,0,2,0,0,0,0,0,2,0,25
351,2,2,2,3,2,0,0,0,2,3,...,0,3,0,0,0,0,0,2,0,9
352,3,2,2,3,2,0,0,0,2,3,...,0,2,0,0,0,0,0,1,0,55
353,1,1,1,2,0,0,0,0,0,0,...,0,0,0,1,0,0,0,2,0,45
354,2,0,1,2,0,0,0,0,0,0,...,0,0,0,0,0,0,0,2,0,56
355,2,3,2,3,2,0,0,0,3,2,...,0,3,0,0,0,0,0,0,0,36
356,2,2,2,2,2,0,0,0,3,0,...,0,3,0,0,0,0,0,0,0,75
357,2,2,2,0,1,0,0,0,0,1,...,0,1,0,0,0,0,0,2,0,45
358,2,3,2,1,0,0,0,0,2,2,...,0,2,0,0,0,0,0,3,0,24
359,2,2,0,0,0,0,0,0,0,0,...,0,0,0,2,0,0,0,1,0,40
360,2,2,1,1,0,0,0,0,0,0,...,0,0,0,3,0,0,0,1,0,25
361,2,1,1,0,1,0,0,0,0,0,...,0,0,0,1,0,0,0,2,0,25
362,3,2,1,0,1,0,0,0,0,0,...,0,1,0,1,0,0,0,2,0,36
363,3,2,2,2,3,2,0,2,0,0,...,3,0,3,0,3,0,0,2,3,28
364,2,1,3,1,2,3,0,2,0,0,...,3,0,2,0,1,0,0,2,3,50
365,3,2,2,0,0,0,0,0,3,3,...,0,2,0,0,0,0,0,3,0,35

In [0]:
x_test

,erythema,scaling,definite_borders,itching,koebner_phenomenon,polygonal_papules,follicular_papules,oral_mucosal_involvement,knee_and_elbow_involvement,scalp_involvement,...,focal_hypergranulosis,disappearance_of_the_granular_layer,vacuolisation_and_damage_of_basal_layer,spongiosis,saw-tooth_appearance_of_retes,follicular_horn_plug,perifollicular_parakeratosis,inflammatory_monoluclear_inflitrate,band-like_infiltrate,age
247,2,2,2,0,0,0,0,0,2,2,...,0,2,0,0,0,0,0,2,0,62
127,2,2,2,2,3,2,0,3,0,0,...,2,0,3,0,3,0,0,3,3,44
230,3,2,0,1,0,0,0,0,0,1,...,0,0,0,2,0,0,0,3,0,30
162,3,2,2,2,0,2,0,2,0,0,...,2,0,1,1,1,0,0,2,2,22
159,3,2,2,1,0,0,0,0,0,0,...,0,0,0,3,0,0,0,2,0,47
296,2,1,1,3,0,0,1,0,0,0,...,0,0,0,0,0,0,0,2,0,19
208,2,3,2,0,0,0,0,0,2,3,...,0,0,0,0,0,0,0,2,0,33
146,3,2,0,3,0,0,0,0,0,0,...,0,0,0,3,0,0,0,2,0,52
277,2,2,2,1,0,0,0,0,0,0,...,0,0,0,3,0,0,0,2,0,25
5,2,3,2,0,0,0,0,0,0,0,...,0,0,0,2,0,0,0,1,0,41
357,2,2,2,0,1,0,0,0,0,1,...,0,1,0,0,0,0,0,2,0,45
342,2,0,1,2,0,0,0,0,0,0,...,0,0,0,0,0,0,0,2,0,50
65,3,2,2,2,0,2,0,1,0,0,...,2,0,2,0,2,0,0,1,3,60
271,2,2,2,0,0,0,0,0,0,0,...,0,1,0,2,0,0,0,3,0,48
188,3,2,0,2,0,0,0,0,0,0,...,0,0,0,3,0,0,0,3,0,55
102,3,3,3,2,2,0,0,0,2,2,...,0,2,0,0,0,0,0,3,0,43
249,2,1,1,2,2,2,0,2,0,0,...,2,0,2,2,3,0,0,2,3,50
311,2,2,2,1,0,0,0,0,2,2,...,0,2,0,0,0,0,0,2,0,36
327,1,1,2,3,2,3,0,2,0,0,...,2,0,2,0,2,0,0,2,3,49
250,2,2,2,2,3,3,0,2,0,0,...,2,0,2,3,2,0,0,3,2,40
106,1,1,0,1,1,0,0,0,0,0,...,0,0,0,2,0,0,0,2,0,60
270,2,2,1,0,1,0,0,0,0,0,...,0,1,0,3,0,0,0,2,0,62
351,2,2,2,3,2,0,0,0,2,3,...,0,3,0,0,0,0,0,2,0,9
287,2,1,2,1,0,2,0,2,0,0,...,2,0,2,0,2,0,0,3,3,40
67,1,1,0,1,3,0,0,0,0,0,...,0,0,0,2,0,0,0,2,0,21
147,1,1,0,3,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,27
201,1,1,0,1,0,0,2,0,0,0,...,0,0,0,0,0,0,0,2,0,25
363,3,2,2,2,3,2,0,2,0,0,...,3,0,3,0,3,0,0,2,3,28
224,2,1,3,3,0,0,0,0,0,0,...,0,0,0,1,0,0,0,1,0,36
310,3,2,2,0,0,0,0,0,0,1,...,0,2,0,0,0,0,0,2,0,50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
334,2,0,1,3,0,0,0,0,0,0,...,0,0,0,0,0,0,0,3,0,63
346,2,2,2,1,0,0,0,0,0,0,...,0,1,0,2,0,0,0,2,0,40
268,2,2,1,1,0,0,2,0,0,0,...,0,0,0,2,0,1,2,2,0,8
213,2,2,2,2,1,3,0,2,0,0,...,3,2,2,2,2,0,0,3,3,30
39,3,3,2,0,0,0,0,0,2,2,...,0,0,0,0,0,0,0,1,0,46
353,1,1,1,2,0,0,0,0,0,0,...,0,0,0,1,0,0,0,2,0,45
90,3,2,1,3,0,0,0,0,0,0,...,0,0,0,3,0,0,0,1,0,50
321,2,2,2,0,1,0,0,0,0,0,...,0,1,0,2,0,0,0,2,0,32
59,3,3,0,3,0,0,0,0,0,0,...,0,0,0,3,0,0,0,2,0,33
12,3,3,1,2,0,0,0,0,0,1,...,0,0,0,2,0,0,0,1,0,22
312,2,2,3,3,2,3,0,1,0,0,...,2,0,3,0,3,0,0,2,3,26
107,1,1,1,1,1,0,0,0,1,1,...,0,0,0,0,0,0,0,2,0,38
91,2,1,0,2,0,0,0,0,0,0,...,0,0,0,0,0,0,0,2,0,43
234,3,2,3,0,1,0,0,0,1,2,...,0,2,0,0,0,0,0,2,0,65
365,3,2,2,0,0,0,0,0,3,3,...,0,2,0,0,0,0,0,3,0,35
131,2,2,2,3,2,0,0,0,1,1,...,0,2,0,0,0,0,0,3,0,40
29,1,1,2,3,2,2,0,3,0,0,...,3,0,3,0,3,1,0,2,3,50
85,2,2,2,3,3,0,0,0,0,2,...,0,0,0,0,0,0,0,2,0,30
58,1,1,1,0,0,0,0,0,0,0,...,0,1,0,1,0,0,0,1,0,25
163,2,2,0,0,0,0,2,0,1,1,...,0,0,0,1,0,1,2,1,0,10
221,2,2,2,1,2,0,0,0,0,0,...,0,0,0,3,0,0,0,2,0,42
218,3,2,1,0,2,0,0,0,0,0,...,0,0,0,3,0,0,0,2,0,45
154,1,0,1,2,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,28
197,3,2,2,0,0,0,0,0,0,0,...,0,0,0,2,0,0,0,2,0,50
359,2,2,0,0,0,0,0,0,0,0,...,0,0,0,2,0,0,0,1,0,40
245,3,3,3,0,0,0,0,0,2,3,...,0,3,0,0,0,0,0,3,0,27
290,2,2,3,2,1,2,0,2,0,0,...,2,0,2,2,2,0,0,3,3,27
175,2,2,2,0,0,0,0,0,3,2,...,0,2,0,0,0,0,0,3,0,30
139,3,3,3,3,2,0,0,0,0,0,...,0,0,0,0,0,0,0,2,0,32
80,3,2,2,2,2,0,0,0,0,0,...,0,0,0,0,0,0,0,2,0,40

In [0]:
from sklearn.datasets import load_iris
from sklearn.linear_model import LogisticRegression

In [0]:
logistic_model = LogisticRegression(random_state = 0, solver = 'lbfgs', multi_class = 'multinomial').fit(x_train,y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:758: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)

In [0]:
p = logistic_model.score(x_test,y_test)

In [0]:
p

0.9818181818181818

In [0]:
from sklearn.naive_bayes import GaussianNB
naivemodel = GaussianNB()
naivemodel.fit(x_train,y_train)
y_predict = naivemodel.predict(x_test)
from sklearn.metrics import confusion_matrix
conf = confusion_matrix(y_test, y_predict)
conf

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

array([[35,  0,  0,  0,  0,  0],
       [ 0,  7,  0, 11,  1,  0],
       [ 0,  0, 23,  0,  0,  0],
       [ 0,  0,  0, 17,  0,  0],
       [ 0,  0,  0,  0, 13,  0],
       [ 0,  0,  0,  0,  0,  3]])

In [0]:
y_predict = naivemodel.predict(x_test)
from sklearn.metrics import confusion_matrix
conf = confusion_matrix(y_test, y_predict)
conf

array([[35,  0,  0,  0,  0,  0],
       [ 0,  7,  0, 11,  1,  0],
       [ 0,  0, 23,  0,  0,  0],
       [ 0,  0,  0, 17,  0,  0],
       [ 0,  0,  0,  0, 13,  0],
       [ 0,  0,  0,  0,  0,  3]])

In [0]:
from sklearn.linear_model import SGDClassifier
sgd = SGDClassifier(loss = 'modified_huber',shuffle = True, random_state = 101)
sgd.fit(x_train,y_train)

r = sgd.score(x_test,y_test)
r

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/stochastic_gradient.py:166: FutureWarning: max_iter and tol parameters have been added in SGDClassifier in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

0.5545454545454546

In [0]:
y_predict = sgd.predict(x_test)

In [0]:
from sklearn.metrics import confusion_matrix
conf = confusion_matrix(y_test, y_predict)
conf

array([[10,  0,  0,  0, 24,  1],
       [ 0,  9,  0,  0, 10,  0],
       [ 0,  0, 23,  0,  0,  0],
       [ 0,  0,  0,  3, 14,  0],
       [ 0,  0,  0,  0, 13,  0],
       [ 0,  0,  0,  0,  0,  3]])

In [0]:
from sklearn.svm import SVC
svm = SVC(kernel = "linear", C = 0.025, random_state = 101)
svm.fit(x_train, y_train)
s = svm.score(x_test,y_test)
s

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

0.990909090909091

In [0]:
y_predict = svm.predict(x_test)

In [0]:
from sklearn.metrics import confusion_matrix
conf = confusion_matrix(y_test, y_predict)
conf

array([[35,  0,  0,  0,  0,  0],
       [ 0, 19,  0,  0,  0,  0],
       [ 0,  0, 23,  0,  0,  0],
       [ 0,  1,  0, 16,  0,  0],
       [ 0,  0,  0,  0, 13,  0],
       [ 0,  0,  0,  0,  0,  3]])

**The best we got till in our inscpection in SVM having more than 99% Accuracy,
And the worst classifier known till now is Stochastic Gradient Descent**

In [0]:
from sklearn import svm, datasets
from sklearn.model_selection import GridSearchCV

parameters = {'kernel':('linear', 'rbf'), 'C':[1, 10]}
svc = svm.SVC(gamma="scale")
clf = GridSearchCV(svc, parameters, cv=5)
clf.fit(x_train, y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_search.py:841: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

GridSearchCV(cv=5, error_score='raise-deprecating',
       estimator=SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False),
       fit_params=None, iid='warn', n_jobs=None,
       param_grid={'kernel': ('linear', 'rbf'), 'C': [1, 10]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=0)

In [0]:
finalscore = clf.score(x_test,y_test)

In [0]:
finalscore

0.9727272727272728